# Generated by Django 3.2.6 on 2021-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
