# Generated by Django 3.2.6 on 2021-10-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_drug_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugbulkupload',
            name='uploaded_by',
            field=models.CharField(default='Admin', max_length=40),
            preserve_default=False,
        ),
    ]
