# Generated by Django 3.2.6 on 2021-10-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_drugbulkupload_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='phase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
