# Generated by Django 3.2.6 on 2021-10-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adddrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddrug',
            name='drugFormula',
        ),
        migrations.AddField(
            model_name='adddrug',
            name='biologicalDescription',
            field=models.TextField(blank=True, verbose_name='Biological Description'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='personName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name of Person'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='drugName',
            field=models.CharField(max_length=50, verbose_name='Drug name'),
        ),
    ]
