# Generated by Django 3.2.6 on 2021-10-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211029_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddrug',
            name='MOA1',
            field=models.CharField(blank=True, max_length=25, verbose_name='MOA(1)'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='moa',
            field=models.CharField(blank=True, max_length=25, verbose_name='moa'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='pathway',
            field=models.CharField(blank=True, max_length=50, verbose_name='Path Way'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='pathway1',
            field=models.CharField(blank=True, max_length=25, verbose_name='Path Way(1)'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='references',
            field=models.TextField(blank=True, max_length=25, verbose_name='References'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='source',
            field=models.CharField(blank=True, max_length=25, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='target1',
            field=models.CharField(blank=True, max_length=25, verbose_name='Path Way(1)'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='researchArea',
            field=models.TextField(blank=True, max_length=100, verbose_name='Research Area'),
        ),
    ]
