# Generated by Django 3.2.6 on 2021-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211029_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddrug',
            name='Type',
            field=models.CharField(blank=True, max_length=25, verbose_name='MOA(1)'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='UniProt',
            field=models.CharField(blank=True, max_length=25, verbose_name='Path Way(1)'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='activity',
            field=models.CharField(blank=True, max_length=25, verbose_name='moa'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='importantNotes',
            field=models.TextField(blank=True, max_length=100, verbose_name='Important Notes'),
        ),
    ]
