# Generated by Django 3.2.6 on 2021-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211029_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddrug',
            name='MOA1',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='UniProt',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='biologicalDescription',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='importantNotes',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='moa',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='references',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='researchArea',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='source',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='status',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='target1',
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='pathway',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pathway'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='pathway1',
            field=models.CharField(blank=True, max_length=25, verbose_name='Pathway(1)'),
        ),
    ]
