# Generated by Django 3.2.6 on 2021-11-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211030_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddrug',
            name='isInvitro',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='isInvivo',
        ),
        migrations.RemoveField(
            model_name='adddrug',
            name='vitvio',
        ),
        migrations.AddField(
            model_name='adddrug',
            name='exvivo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Exvivo'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='inference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Inference'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='invitro',
            field=models.CharField(default=True, max_length=100, verbose_name='Invitro'),
        ),
        migrations.AddField(
            model_name='adddrug',
            name='invivo',
            field=models.CharField(default=True, max_length=100, verbose_name='Invivo'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='drugName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='organisation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='results',
            field=models.CharField(blank=True, max_length=100, verbose_name='Activity Results'),
        ),
    ]
