# Generated by Django 3.2.6 on 2021-11-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211101_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddrug',
            name='drugName',
            field=models.CharField(max_length=100, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='invitro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Invitro'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='invivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Invivo'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='organisation',
            field=models.CharField(max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='personName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name of Person'),
        ),
        migrations.AlterField(
            model_name='adddrug',
            name='results',
            field=models.CharField(max_length=100, verbose_name='Activity Results'),
        ),
    ]
