# Generated by Django 3.2.6 on 2021-12-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211102_1056'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drug',
            name='main_drug_cas_ee2b0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='drug',
            name='main_drug_pubchem_dcb991_idx',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='cas',
            new_name='cas_number',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='pubchem',
            new_name='pubchemcid',
        ),
        migrations.AddField(
            model_name='drug',
            name='administration_route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='hba',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='hbd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='logp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='mw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='nochiralcentres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='psa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='rotbonds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='similar_drugs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['cas_number'], name='main_drug_cas_num_4fe383_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['pubchemcid'], name='main_drug_pubchem_b973f2_idx'),
        ),
    ]
