# Generated by Django 3.2.6 on 2022-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_drugbulkupload_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='rank_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
