# Generated by Django 3.2.6 on 2022-01-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_drug_filters_passed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drug',
            name='main_drug_chebl_a8f84c_idx',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='chebl',
            new_name='chebi',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='chembank',
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['chebi'], name='main_drug_chebi_fcabd3_idx'),
        ),
    ]
