# Generated by Django 3.2.6 on 2022-04-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
