# Generated by Django 3.2.6 on 2022-04-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='relevant',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
