# Generated by Django 3.2.6 on 2022-04-27 13:07

from django.conf import settings
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_contributeddrug_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='article',
            name='assigned_to',
            field=models.ForeignKey(default=None, null=True, on_delete=main.models.REASSIGN, to=settings.AUTH_USER_MODEL),
        ),
    ]
