# Generated by Django 3.2.6 on 2022-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220506_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='filters_failed',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
