# Generated by Django 3.2.6 on 2021-10-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('sent_on', models.DateField(auto_now=True, verbose_name='Invite was sent out on')),
            ],
            options={'verbose_name': 'Invite Members', 'verbose_name_plural': 'Invite'},
        ),
        migrations.AddField(
            model_name='user',
            name='google_oauth_id',
            field=models.TextField(blank=True, default=None, help_text='Used for social oauth', null=True, verbose_name='Google Token ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.TextField(default='https://randomuser.me/api/portraits/lego/2.jpg'),
        ),
    ]
