# Generated by Django 3.2.6 on 2021-10-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_visitor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('session_key', 'page_visited', 'timestamp')},
        ),
    ]
