# Generated by Django 3.2.6 on 2022-01-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='admin_access',
            field=models.BooleanField(default=False, verbose_name='Admin Access'),
        ),
    ]
