# Generated by Django 3.2.6 on 2022-02-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invitee_admin_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='drug_overview',
            field=models.BooleanField(default=False),
        ),
    ]
