# Generated by Django 3.2.6 on 2022-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_visitor_drug_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='admin_access',
            field=models.SmallIntegerField(default=0, verbose_name='Permission level on CoviRx'),
        ),
    ]
