# Generated by Django 3.2.6 on 2022-04-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_invitee_admin_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
