# Generated by Django 3.2.6 on 2022-04-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_invitee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If user is a non-superuser staff member. Unchecking this would lead to reassignment of articles.', verbose_name='active'),
        ),
    ]
