# Generated by Django 3.2.6 on 2022-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='User will not be able to login. If user is a non-superuser staff member. Unchecking this would lead to reassignment of articles.', verbose_name='active'),
        ),
    ]
